/* Generated by tex3ds */
#pragma once

#define sprites_player_run_1_idx 0
#define sprites_player_run_2_idx 1
#define sprites_player_run_3_idx 2
#define sprites_player_run_4_idx 3
#define sprites_player_run_5_idx 4
#define sprites_player_run_6_idx 5
